### ISSUE TITLE
Get/store user ID at log in

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade-dashboard#17]
Currently being logged in/out is a boolean. You're logged in or you aren't.

I'd like to retrieve the user id at login using the `v2/whoami` endpoint.

I'd like this to be stored in a string. So, `!userID` will mean not logged in. A non-empty value will mean logged in _and_ will disclose the user's ID. The boolean will go away.

This ID can and will be used later in other places.

**Comment by DhairyaBahl** [comment]
@krancour Kindly assign this to me.

**Comment by krancour** [comment]
You got it

**Comment by krancour** [comment]
Can you open a draft PR so I can see what you're talking about more clearly?

**Comment by DhairyaBahl** [comment]
@krancour 

In this function `handleLogin`, after logging in, I will get the `thirdPartyAuthDetails.token` 

![image](https://user-images.githubusercontent.com/71627983/158223110-266f4fca-8c8b-42ce-8d0b-9bf6e6cb8352.png)

and I have to use that in whoAmI function. So I am asking how can I use the newly acquired token in this function. I cannot pass it over there explicitly. I can only create a new instance of APIClient which will break the singleton nature of that. So, ig we can't do that also.

<img width="498" alt="image" src="https://user-images.githubusercontent.com/71627983/158223217-68e15d28-a888-40e6-9058-3e918c481603.png">
