### ISSUE TITLE
Contributing.md

### ISSUE THREAD

**Issue by DhairyaBahl** [brigadecore/brigade-dashboard#22]
### Description
There is no `CONTRIBUTING.md` file which is breaking the link in `Readme.md`.

### Fix 
Add a `CONTRIBUTING.md` file in the main code.

### Issue Type
documentation, good first issue

**Comment by krancour** [comment]
Nice catch @DhairyaBahl.

Anyone who wants to tackle this can resolve it by copying the boilerplate `CONTRIBUTING.md` from the main brigadecore/brigade repo. That itself just points elsewhere.

**Comment by DhairyaBahl** [comment]
@krancour I will fix this asap. Kindly assign it to me. Or we can just leave it for some time coz it's a great issue for first time contributors. Its ur call.

**Comment by krancour** [comment]
Assigned
