### ISSUE TITLE
Conflicting Dependencies

### ISSUE THREAD

**Issue by DhairyaBahl** [brigadecore/brigade-dashboard#23]
### Description
Some react dependency is conflicting when I am trying to build the code in my local environment.

<img width="439" alt="image" src="https://user-images.githubusercontent.com/71627983/156433754-8e5394d3-b643-4665-8b88-202b1383b676.png">

**Comment by krancour** [comment]
@DhairyaBahl it looks like maybe you used `npm install`? This project actually uses `yarn` as the package manager. `yarn install` should use the versions that `yarn.lock` has pinned us to. Let me know if that helps.

**Comment by DhairyaBahl** [comment]
@krancour I believe that this issue that I was facing only exists in the case of NPM. I tried with yarn and it successfully built it. So, I guess it is nothing to be worried about.

I suggest you to close this issue.
