### ISSUE TITLE
[chore] Setup ESLint and Prettier

### ISSUE THREAD

**Issue by CIPHERTron** [brigadecore/brigade-dashboard#39]
Currently, this codebase isn't using any code formatter or linter. It would be great if we have a linter to highlight errors and formatter to prettify the code.

We can use ES Lint for code linting & managing errors and Prettier for code formatting.

ESLint is a tool for identifying and reporting on patterns found in JS/TS code, with the goal of making code more consistent and avoiding bugs.

Prettier is a tool that automatically makes your code more readable and consistent with your project's style guide. It integrates with your editor, so your code is tidied up every time you save your changes.

This is just to ensure uniform coding standards :)

References:
ESLint: https://eslint.org/
Prettier: https://prettier.io/

**Comment by krancour** [comment]
Half of this (the linter half) is already in-progress. See #37.

prettier also seems like a good option. I was reading up on it last night after another contributor mentioned it. I want to play around with it a bit before committing to it, but I'm fairly certain that's where we'll end up.
