### ISSUE TITLE
`Antipattern` Copying Props to State

### ISSUE THREAD

**Issue by DhairyaBahl** [brigadecore/brigade-dashboard#40]
### Description

It breaks the concept of single source of truth in React. We can use get [getDerivedStateFromProps](https://reactjs.org/docs/react-component.html#static-getderivedstatefromprops) as an alternative or we can simply use it as props instead of adding it in state. This will lead to more bugs in near future.

<img width="328" alt="image" src="https://user-images.githubusercontent.com/71627983/157438295-628e1968-7cb1-41ce-b45f-b2704597fac3.png">

**Comment by krancour** [comment]
And thanks for pointing this out!

**Comment by DhairyaBahl** [comment]
> I agree this is generally an anti-pattern.
> 
> In this specific case, there was a reason I did it this way.
> 
> The login control is only responsible for displaying the login or logout button and executing the correct handler when the button is clicked. If the control makes no assumptions about what the handler passed into it does, then it's possible that the component that passed the handler to the `LoginControl` _doesn't_ update its own state in that handler and that creates the possibility that nothing compels the `LoginControl` to be re-rendered.
> 
> To work around that, I gave the `LoginControl` its own internal state that is only _initialized_ from the props. Let's just say it made sense to me at the time (I'm new to react, but when I wrote that bit, I was _very_ new to it).
> 
> A few months later, I'm finding my reasoning doesn't hold up. Sure -- the component that passed the handlers to the `LoginControl` could goof and _not_ update its own state and _not_ force the `LoginControl` to re-render... but per my statement that "the login control is only responsible for displaying the login or logout button and executing the correct handler," _that's not the `LoginControl`'s problem, is it?_
> 
> So... I agree.
> 
> Already have the fix in-progress.

Ohh ! Understood ! 🙂
