### ISSUE TITLE
Web site description needs update

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade-dashboard#5]
`index.html` currently has this:

```htlm
<meta name="description" content="Web site created using create-react-app"/>
```

This should be updated. I'm not feeling creative, at the moment. "Brigade Dashboard" would suffice, but if whoever grabs this issue wants to propose something else, that's cool, too.

**Comment by DhairyaBahl** [comment]
@krancour Kindly assign this issue to me ! I would love to start my contributions in brigade-dashboard with this issue.

PS: I also wanted to ask if I can get myself assigned to multiple issues at the same time ?

**Comment by krancour** [comment]
>  I also wanted to ask if I can get myself assigned to multiple issues at the same time?

Yup! Totally can.

**Comment by krancour** [comment]
Also...

> I am trying to learn what brigade actually is.

This video's about 7 minutes and is probably the most thorough introduction you can get in so short a period of time: https://www.youtube.com/watch?v=VFyvYOjm6zc
