### ISSUE TITLE
Setup a CI pipeline for automated PR previews

### ISSUE THREAD

**Issue by CIPHERTron** [brigadecore/brigade-dashboard#58]
Currently, we don't have any previews whenever a PR is opened. We have to pull the changes to local in-order to review. What if we get a preview of the PR whenever a new PR is opened?

It would be great if we can deploy the development version of the brigade dashboard to vercel or netlify since it provides automated deploy of PR and provides a preview link or else we can use other CI tools like Circlie CI.

Reference:
Vercel: https://vercel.com/
Netlify: https://www.netlify.com/
Circle CI: https://circleci.com/

**Comment by krancour** [comment]
> Currently, we don't have any previews whenever a PR is opened. We have to pull the changes to local in-order to review. What if we get a preview of the PR whenever a new PR is opened?

Great idea.

> It would be great if we can deploy the development version of the brigade dashboard to vercel or netlify

We've used Netlify pretty widely for our docs and other static content. This should be possible.

> or else we can use other CI tools like Circlie CI

Netlify can do what we need without the need for any additional automation, but note that Brigade itself is an automation platform and we "eat our own dogfood," so we turn to Brigade itself for all of our CI needs.

**Comment by krancour** [comment]
This is all set. You'll automatically get previews on Netlify when you open a PR now.
