### ISSUE TITLE
proposal: navbar should stick to the top

### ISSUE THREAD

**Issue by CIPHERTron** [brigadecore/brigade-dashboard#59]
As of now, the navbar doesn't stick to the top which would make it easier for users to navigate between pages.
Also, the footer sticks to the bottom which might not be a great from UI/UX perspective according to me

----

https://user-images.githubusercontent.com/56754747/159470964-287e3eec-4fd7-424d-aec8-9fedc3cea8d0.mov

**Comment by krancour** [comment]
@CIPHERTron let's treat this as two separate issues.

LEt's have this issue be about the header and I'll open another about the footer.

Let's also discuss this more before deciding it's a bug.

**Comment by CIPHERTron** [comment]
> I'm willing to have this conversation again in the future as the app evolves. Over time, we may find that pinning to the top makes more sense.

Oh yeah, this was actually my personal preference but your points absolutely make sense. Let's keep this as a proposal and we can discuss about it in the upcoming community meetings maybe?

**Comment by krancour** [comment]
I'm closing this issue for now.
