### ISSUE TITLE
When viewing events/jobs, should gray out log tabs if the user doesn't have access

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade-dashboard#65]
The backend already will prevent log access by unauthorized users, so this is a matter of UX only.

When loading an event on the event page ([right here](https://github.com/brigadecore/brigade-dashboard/blob/main/src/Event.tsx#L41-L45)) we should retrieve the user's permissions WRT to the project that the event belongs to. If the user does _not_ have the `PROJECT_USER` role, then log tabs (for worker, jobs, etc.) should all be grayed out.

cc @DhairyaBahl tagging you because this is closely related to what you recently worked on in #48. This issue may interest you. If so, lmk and I'll assign it.

**Comment by DhairyaBahl** [comment]
@krancour Thanks for Mention. I would love to work on this issue. Kindly assign this to me.

**Comment by krancour** [comment]
@DhairyaBahl it's yours.
